// <auto-generated />
using System;
using ChadWebCalendar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChadWebCalendar.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ChadWebCalendar.Data.Duty", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Accessed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NRepetitions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Duties");
                });

            modelBuilder.Entity("ChadWebCalendar.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemindEveryNDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeZone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkingHoursFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkingHoursTo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelectedProjectId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChadWebCalendar.Data.Event", b =>
                {
                    b.HasBaseType("ChadWebCalendar.Data.Duty");

                    b.Property<DateTime>("FinishesAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemindNMinutesBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("TEXT");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ChadWebCalendar.Data.Project", b =>
                {
                    b.HasBaseType("ChadWebCalendar.Data.Duty");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconNumber")
                        .HasColumnType("TEXT");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ChadWebCalendar.Data.Task", b =>
                {
                    b.HasBaseType("ChadWebCalendar.Data.Duty");

                    b.Property<bool>("AllowedToDistribute")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PredecessorFK")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("TimeTakes")
                        .HasColumnType("TEXT");

                    b.HasIndex("PredecessorFK");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ChadWebCalendar.Data.Duty", b =>
                {
                    b.HasOne("ChadWebCalendar.Data.User", "User")
                        .WithMany("Duties")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChadWebCalendar.Data.User", b =>
                {
                    b.HasOne("ChadWebCalendar.Data.Project", "SelectedProject")
                        .WithMany()
                        .HasForeignKey("SelectedProjectId");

                    b.Navigation("SelectedProject");
                });

            modelBuilder.Entity("ChadWebCalendar.Data.Event", b =>
                {
                    b.HasOne("ChadWebCalendar.Data.Duty", null)
                        .WithOne()
                        .HasForeignKey("ChadWebCalendar.Data.Event", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChadWebCalendar.Data.Project", b =>
                {
                    b.HasOne("ChadWebCalendar.Data.Duty", null)
                        .WithOne()
                        .HasForeignKey("ChadWebCalendar.Data.Project", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChadWebCalendar.Data.Task", b =>
                {
                    b.HasOne("ChadWebCalendar.Data.Duty", null)
                        .WithOne()
                        .HasForeignKey("ChadWebCalendar.Data.Task", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChadWebCalendar.Data.Task", "Predecessor")
                        .WithMany()
                        .HasForeignKey("PredecessorFK");

                    b.HasOne("ChadWebCalendar.Data.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Predecessor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ChadWebCalendar.Data.User", b =>
                {
                    b.Navigation("Duties");
                });
#pragma warning restore 612, 618
        }
    }
}
